import * as Print from 'expo-print';
import * as FileSystem from 'expo-file-system';
import { Invoice } from './invoiceService';

class PDFService {
  async generatePDF(invoice: Invoice): Promise<string> {
    const html = this.buildHTML(invoice);
    const { uri } = await Print.printToFileAsync({ html, base64: false });

    // Move to a named file in cache
    const dest = `${FileSystem.cacheDirectory}${invoice.invoiceNumber}.pdf`;
    await FileSystem.moveAsync({ from: uri, to: dest });
    return dest;
  }

  private buildHTML(inv: Invoice): string {
    const taxAmount = inv.total - inv.subtotal;
    const rows = inv.lineItems
      .map(
        item => `
        <tr>
          <td>${item.name}</td>
          <td style="text-align:center">${item.qty}</td>
          <td style="text-align:right">$${item.unitPrice.toFixed(2)}</td>
          <td style="text-align:right">$${(item.qty * item.unitPrice).toFixed(2)}</td>
        </tr>`,
      )
      .join('');

    return `<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<style>
  * { margin:0; padding:0; box-sizing:border-box; }
  body { font-family: -apple-system, Helvetica, sans-serif; color:#1A1A2E; padding:48px; }
  .header { display:flex; justify-content:space-between; align-items:flex-start; margin-bottom:40px; }
  .brand { font-size:20px; font-weight:700; color:#534AB7; }
  .brand-sub { font-size:11px; color:#9B98B8; margin-top:2px; }
  .inv-meta { text-align:right; }
  .inv-num { font-size:17px; font-weight:600; }
  .inv-date { font-size:12px; color:#6B6882; margin-top:3px; }
  .badge { display:inline-block; background:#E1F5EE; color:#0F6E56; font-size:10px; font-weight:600; padding:3px 10px; border-radius:20px; margin-top:5px; text-transform:uppercase; }
  hr { border:none; border-top:1px solid #EEEDFE; margin:24px 0; }
  .parties { display:flex; justify-content:space-between; margin-bottom:36px; }
  .party label { font-size:10px; font-weight:600; color:#9B98B8; text-transform:uppercase; letter-spacing:.5px; display:block; margin-bottom:3px; }
  .party-name { font-size:14px; font-weight:600; }
  table { width:100%; border-collapse:collapse; margin-bottom:20px; }
  thead tr { border-bottom:2px solid #EEEDFE; }
  th { font-size:10px; font-weight:600; color:#9B98B8; text-transform:uppercase; padding:8px 0; text-align:left; }
  th:nth-child(2){ text-align:center; } th:nth-child(3),th:nth-child(4){ text-align:right; }
  tbody tr { border-bottom:.5px solid #F1EFF8; }
  td { font-size:13px; padding:11px 0; }
  .totals { margin-left:auto; width:220px; }
  .t-row { display:flex; justify-content:space-between; padding:5px 0; font-size:13px; color:#6B6882; }
  .t-grand { border-top:2px solid #EEEDFE; margin-top:6px; padding-top:10px; font-size:17px; font-weight:700; color:#1A1A2E; }
  .t-grand span:last-child { color:#534AB7; }
  .notes { background:#F8F7FC; border-left:3px solid #534AB7; padding:12px 14px; border-radius:0 8px 8px 0; margin-top:36px; }
  .notes-lbl { font-size:10px; font-weight:600; color:#534AB7; text-transform:uppercase; margin-bottom:3px; }
  .notes-txt { font-size:12px; color:#6B6882; }
  .footer { margin-top:48px; text-align:center; font-size:10px; color:#A09CC0; }
</style>
</head>
<body>

<div class="header">
  <div>
    <div class="brand">Receipt2Invoice</div>
    <div class="brand-sub">Professional Invoice</div>
  </div>
  <div class="inv-meta">
    <div class="inv-num">${inv.invoiceNumber}</div>
    <div class="inv-date">${inv.date}</div>
    <div class="badge">${inv.status}</div>
  </div>
</div>

<hr>

<div class="parties">
  <div class="party">
    <label>From</label>
    <div class="party-name">${inv.merchant}</div>
  </div>
  ${inv.customerName ? `<div class="party" style="text-align:right"><label>Bill to</label><div class="party-name">${inv.customerName}</div></div>` : ''}
</div>

<table>
  <thead><tr><th>Description</th><th>Qty</th><th>Unit price</th><th>Amount</th></tr></thead>
  <tbody>${rows}</tbody>
</table>

<div class="totals">
  <div class="t-row"><span>Subtotal</span><span>$${inv.subtotal.toFixed(2)}</span></div>
  <div class="t-row"><span>Tax (${inv.taxRate}%)</span><span>$${taxAmount.toFixed(2)}</span></div>
  <div class="t-row t-grand"><span>Total</span><span>$${inv.total.toFixed(2)}</span></div>
</div>

${inv.paymentNotes ? `<div class="notes"><div class="notes-lbl">Payment terms</div><div class="notes-txt">${inv.paymentNotes}</div></div>` : ''}

<div class="footer">Generated by Receipt2Invoice · ${new Date().toLocaleDateString()}</div>
</body>
</html>`;
  }
}

export const pdfService = new PDFService();
